### ISSUE TITLE
DeadObjectException arise when reconnecting to the GATT server

### ISSUE THREAD

**Issue by HQHAN** [FirstBuild/FirstBuild-Mobile-Android#15]
Issue )
06-16 15:33:29.031 31166-31258/com.firstbuild.androidapp E/BluetoothGatt: android.os.DeadObjectException
                                                                              at android.os.BinderProxy.transactNative(Native Method)
                                                                              at android.os.BinderProxy.transact(Binder.java:503)
                                                                              at android.bluetooth.IBluetoothGatt$Stub$Proxy.writeDescriptor(IBluetoothGatt.java:1247)
                                                                              at android.bluetooth.BluetoothGatt.writeDescriptor(BluetoothGatt.java:1221)
                                                                              at com.firstbuild.commonframework.blemanager.BleOperationSetNotification.execute(BleOperationSetNotification.java:63)
                                                                              at com.firstbuild.commonframework.blemanager.BleManager.executeOperation(BleManager.java:658)
                                                                              at com.firstbuild.commonframework.blemanager.BleManager.doOperation(BleManager.java:487)
                                                                              at com.firstbuild.commonframework.blemanager.BleManager.cancelCurrentOperation(BleManager.java:424)
                                                                              at com.firstbuild.commonframework.blemanager.BleManager$3.doInBackground(BleManager.java:473)
                                                                              at com.firstbuild.commonframework.blemanager.BleManager$3.doInBackground(BleManager.java:456)
                                                                              at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                              at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                              at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                              at java.lang.Thread.run(Thread.java:818)

Solve )
Investigate and solve the excetpion

**Comment by HQHAN** [comment]
looks like it has been solved indirectly so closing it now
