### ISSUE TITLE
[Opal] Crash issues

### ISSUE THREAD

**Issue by HQHAN** [FirstBuild/FirstBuild-Mobile-Android#22]
Issue )

BUG 2
App is crashing when selecting either the Opal or the Paragon to add. So far we have only seen a successful pairing on Android Phones with 6.X (Marshmallow)
Attaching: paragon-crash-adding-product-1.06.mov and paragon-crash-adding-product-log-1.06.rtf

BUG 3
App will not open on Galaxy S3 4.4.2. When trying to open the App displays the Unfortunately 1B has stopped. 
Attaching: paragon-app-crash-GalaxyS3-4.4.2-v1.06.rtf and paragon-app-crash-GalaxyS3-4.4.2-v1.06.mov

**Comment by HQHAN** [comment]
Looks like the apk built using instant run causes crash like below

Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.tools.fd.runtime.BootstrapApplication" on path: DexPathList[[zip file "/data/app/com.firstbuild.androidapp-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.firstbuild.androidapp-1, /vendor/lib, /system/lib]]
                                                                             at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:67)
                                                                             at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
                                                                             at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
                                                                             at android.app.Instrumentation.newApplication(Instrumentation.java:981)
                                                                             at android.app.LoadedApk.makeApplication(LoadedApk.java:511)
                                                                             at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4588) 
                                                                             at android.app.ActivityThread.access$1600(ActivityThread.java:169) 
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1340) 
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                             at android.os.Looper.loop(Looper.java:146) 
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5487) 
                                                                             at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                             at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283) 
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099) 
                                                                             at dalvik.system.NativeStart.main(Native Method)

**Comment by HQHAN** [comment]
close as relevant patch is pushed
