### ISSUE TITLE
[Opal] App crash on Dashboard

### ISSUE THREAD

**Issue by HQHAN** [FirstBuild/FirstBuild-Mobile-Android#24]
Issue )

06-21 10:14:52.110 27665-27794/com.firstbuild.androidapp E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #7
                                                                           Process: com.firstbuild.androidapp, PID: 27665
                                                                           java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                               at android.os.AsyncTask$3.done(AsyncTask.java:309)
                                                                               at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                                               at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                                               at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                               at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                               at java.lang.Thread.run(Thread.java:818)
                                                                            Caused by: java.util.NoSuchElementException
                                                                               at java.util.LinkedList.removeFirstImpl(LinkedList.java:689)
                                                                               at java.util.LinkedList.removeFirst(LinkedList.java:676)
                                                                               at java.util.LinkedList.poll(LinkedList.java:895)
                                                                               at com.firstbuild.commonframework.blemanager.BleManager.doOperation(BleManager.java:441)
                                                                               at com.firstbuild.commonframework.blemanager.BleManager.cancelCurrentOperation(BleManager.java:424)
                                                                               at com.firstbuild.commonframework.blemanager.BleManager$3.doInBackground(BleManager.java:473)
                                                                               at com.firstbuild.commonframework.blemanager.BleManager$3.doInBackground(BleManager.java:456)
                                                                               at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                               at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                               at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234) 
                                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                               at java.lang.Thread.run(Thread.java:818)

**Comment by HQHAN** [comment]
Hopefully enhancing thread-safety fixed this issue
